[".antidote"]
type = "archive"
url = "https://github.com/mattmc3/antidote/archive/refs/tags/v1.9.4.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

[".tokyonight"]
type = "git-repo"
url = "https://github.com/folke/tokyonight.nvim.git"
refreshPeriod = "168h"
