import = ['~/.config/alacritty/catppuccin-macchiato.toml']
[font]
size = 13
[font.normal]
family = "Hack Nerd Font"
[env]
TERM = "xterm-256color"
[window]
opacity = 0.95
blur = false
[shell]
program = "zsh"
args = ["-l"]
