[packages]
taps = [
  "FelixKratz/formulae",
  "homebrew/bundle",
  "homebrew/linux-fonts",
  "homebrew/services",
  "localsend/localsend",
  "microsoft/git",
]
brews = [
  "athenacli",
  "aws-vault",
  "awscli",
  "bandwhich",
  "bash",
  "bat",
  "biome",
  "bitwarden-cli",
  "bottom",
  "chezmoi",
  "cmake",
  "cmatrix",
  "coreutils",
  "cowsay",
  "curl",
  "duf",
  "entr",
  "exiftool",
  "eza",
  "figlet",
  "fzf",
  "gd",
  "gh",
  "git",
  "git-delta",
  "git-extras",
  "gnupg",
  "gnutls",
  "go",
  "go-task",
  "homebrew/linux-fonts/font-hack-nerd-font",
  "homebrew/linux-fonts/font-fira-code-nerd-font",
  "htop",
  "httpie",
  "jq",
  "just",
  "kubernetes-cli",
  "kustomize",
  "lazygit",
  "litecli",
  "lolcat",
  "make",
  "mariadb",
  "mas",
  "mycli",
  "ncdu",
  "fastfetch",
  "neovim",
  "noti",
  "nyancat",
  "openssh",
  "pgcli",
  "php@8.1",
  "prettyping",
  "procs",
  "pv",
  "ripgrep",
  "speedtest-cli",
  "starship",
  "thefuck",
  "tig",
  "tldr",
  "tmux",
  "tree",
  "tty-clock",
  "yq",
  "zk",
  "zoxide",
]
casks = [
  "alt-tab",
  "bluesnooze",
  "calibre",
  "docker",
  "firefox",
  "font-caskaydia-cove-nerd-font",
  "font-fira-code-nerd-font",
  "font-hack-nerd-font",
  "font-jetbrains-mono-nerd-font",
  "git-credential-manager",
  "keepingyouawake",
  "kitty",
  "lastpass",
  "libreoffice",
  "localsend",
  "moonlight",
  "openscad-snapshot",
  "podman-desktop",
  "postman",
  "powershell",
  "rectangle",
  "scroll-reverser",
  "slack",
  "spotify",
  "steam",
  "syncthing",
  "tableplus",
  "tailscale",
  "telegram",
  "thunderbird-beta",
  "todoist",
  "utm",
  "vlc",
  "zoom",
]
